### ISSUE TITLE
Could you please keep on constructing your code?

### ISSUE THREAD

**Issue by DesmonDay** [THUDM/KBRD#3] opened 2019-09-26 05:22 UTC
Your code is too hard to understand. I can't even find the entrance of the KBRD... Need help!

**Comment by luyulalala** [comment] 2019-09-26 10:05
Hello, I guess a en entrance and maybe you can try it.   bash KBRD-master/scripts/t2t.sh

**Comment by qibinc** [comment] 2019-09-26 16:13
Hi @DesmonDay ,

I'll clean up the code during the National Holiday. Thank you for your patience!

**Comment by DesmonDay** [comment] 2019-10-10 13:16
I met the problem when I run the bash file:

Traceback (most recent call last):
  File "parlai/tasks/redial/train_kbrd.py", line 35, in <module>
    opt = parser.parse_args()
  File "/data/desmon/ParlAI/parlai/core/params.py", line 996, in parse_args
    self.add_extra_args(args)
  File "/data/desmon/ParlAI/parlai/core/params.py", line 820, in add_extra_args
    self.add_task_args(task)
  File "/data/desmon/ParlAI/parlai/core/params.py", line 761, in add_task_args
    agent = get_task_module(t)
  File "/data/desmon/ParlAI/parlai/core/agents.py", line 784, in get_task_module
    my_module = importlib.import_module(module_name)
  File "/home/desmon/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'parlai.tasks.redial'

I am not quite familiar with ParlAI. I have already build the parlai environment, but still failed.  And the module import from 'parlai.scripts.train_model' failed, so I add the following code:
`import sys
sys.path.append('/home/desmon/KBRD/parlai')`

I don't know how to fix the problem. Could you help me?

**Comment by qibinc** [comment] 2019-10-10 13:27
Hi @deshraj ,

Please don't install the parlai module from the ParlAI README. If so, the script will call the installed package of `parlai` instead of this repo, which leads to the missing of `parlai.tasks.redial`. Please uninstall the parlai and run `export PYTHONPATH=/path/to/repo:$PYTHONPATH` (or add this in your bash profile).

**Comment by luyulalala** [comment] 2019-10-12 05:11
I met the problem when I run the bash file:
AttributeError: module 'parlai.agents.kbrd.kbrd' has no attribute 'KbrdAgent'

Did you have the same problem and could you please tell me your solution?
Thanks!

**Comment by DesmonDay** [comment] 2019-10-12 05:54
I met the same problem!!! But have no time to understand and fix it yet. maybe we could ask the author~&nbsp;

---Original---

**Comment by qibinc** [comment] 2019-10-12 11:55
Dear @luyulalala and @DesmonDay ,

I apologize that I haven't spent time examining the code carefully since last refactor. Please wait for some time and I'll fix this and delete the irrelevant components. Thanks for the patience.

**Comment by qibinc** [comment] 2019-10-12 13:29
Hi guys,

I did quite a lot cleaning in the code and fix the above issue. It looks not as messy as before:). However, I still haven't the chance to test and re-run all the experiments, since the GPUs in my lab are all currently occupied by the WWW'20 submission authors. Really sorry about these inconvenience. Please notify me if you encounter further problems and I will make a follow-up update later (after the submission).

**Comment by ahtsham58** [comment] 2020-02-03 15:40
hey @qibinc , 
I am trying to train the first model "bash scripts/both.sh" but getting an error "ImportError: No module named parlai.scripts.train_model". Can you please help how to resolve this..

PS. I just followed the git Readme guidlines to setup the working directory.

**Comment by ahtsham58** [comment] 2020-02-05 10:27
If anyone else faced the same issue..? Would appreciate your feedback as I am new to such stuff..
thanks!

**Comment by qibinc** [comment] 2020-02-05 10:44
Hi @ahtsham58 ,

It seems the project directory is not in your PYTHONPATH and you should add it. Please see https://stackoverflow.com/questions/3402168/permanently-add-a-directory-to-pythonpath.

**Comment by ahtsham58** [comment] 2020-02-05 11:37
Hey, Thanks for the reply. My project directory is in PYTHONPATH as i confirmed it,
I am successful in resolving that above error. BUT..
Now I am facing this issue ""AttributeError: module 'parlai.tasks.redial.agents' has no attribute 'create_agents'

Any leads please...

**Comment by qibinc** [comment] 2020-02-05 12:27
Hi @ahtsham58 ,

Could you give a complete description of your error? I'm not sure what caused the problem based on the information above.

Thanks

**Comment by ahtsham58** [comment] 2020-02-05 12:48
Sorry My bad!
Here is the complete error description while executing both.sh. It occurred while unpacking redial dataset..

`[creating task(s): redial]
Traceback (most recent call last):
  File "/root/KBRD/parlai/core/agents.py", line 756, in _create_task_agents
    create_agent = getattr(my_module, 'create_agents')
AttributeError: module 'parlai.tasks.redial.agents' has no attribute 'create_agents'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "parlai/tasks/redial/train_kbrd.py", line 35, in <module>
    TrainLoop(opt).train()
  File "/root/KBRD/parlai/scripts/train_model.py", line 230, in __init__
    build_dict(opt, skip_if_built=True)
  File "/root/KBRD/parlai/scripts/build_dict.py", line 106, in build_dict
    world_dict = create_task(ordered_opt, dictionary)
  File "/root/KBRD/parlai/core/worlds.py", line 1053, in create_task
    world = create_task_world(opt, user_agents, default_world=default_world)
  File "/root/KBRD/parlai/core/worlds.py", line 1011, in create_task_world
    opt, user_agents, default_world=default_world
  File "/root/KBRD/parlai/core/worlds.py", line 976, in _get_task_world
    task_agents = _create_task_agents(opt)
  File "/root/KBRD/parlai/core/agents.py", line 760, in _create_task_agents
    return create_task_agent_from_taskname(opt)
  File "/root/KBRD/parlai/core/agents.py", line 713, in create_task_agent_from_taskname
    task_agents = teacher_class(opt)
  File "/root/KBRD/parlai/tasks/redial/agents.py", line 61, in __init__
    self.text_dict = pkl.load(open(text_dict_path, "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/root/KBRD/data/redial/text_dict.pkl'
`

**Comment by qibinc** [comment] 2020-02-05 12:51
Hi @ahtsham58 ,

Please follow the instructions in README for downloading the dataset (https://github.com/THUDM/KBRD#dataset). 

The third step, which includes the text_dict.pkl file, has to be downloaded manually. Sorry for the inconvenience!

Best,
Qibin

**Comment by ahtsham58** [comment] 2020-02-05 13:04
Hi,
I have downloaded the redial dataset already. I placed that in
KBRD/data/redial directory. according to the instructions.

The problem is when I execute both.sh script, it download the redial dataset again and i got this error while it is unpacking the data.

both dbpedia and redial datasets are already in my repo..

**Comment by qibinc** [comment] 2020-02-05 13:08
Hi @ahtsham58 ,

That's weird... Could you share your experiment environment and scripts to reproduce the error? Just `bash both.sh xxx xxx`? On my machine (Ubuntu 16, Python 3.6, PyTorch 1.2), it will only download the redial dataset once and will skip the download if there is already a `KBRD/data/redial ` directory so the dict file won't be overwritten.

**Comment by ahtsham58** [comment] 2020-02-05 13:33
Yes, you are right, actually i I did download it but couldnt the find the text_dict.pkl file there. Now I downlaod it again and it worked for me. 

Thank you so much for the urgent replies. 
I Hope you wont mind my queries till the complete reproducibility :)

**Comment by qibinc** [comment] 2020-02-05 17:01
Hi @ahtsham58 ,

I'm grad to see things are working for you. If you meet other problems, please start a new issue (too many different questions in this thread). Thanks!

**Closed as completed by qibinc** 2020-02-05 17:01 UTC
